export const data = {
    "Registro Mercantil": {
        "Actos constitutivos": {
            // Artículo 4, Numeral 1
            "Constitución de compañía": {
                tipo: "petro+porcentaje",
                articulo: 4,
                numeral: 1,
                primerFolio: 1.5,
                folioAdicional: 0.2,
                porcentajeCapital: 0.02 // 2%
            },
            // Artículo 4, Numeral 1
            "Cambio de nombre": {
                tipo: "petro",
                articulo: 4,
                numeral: 1,
                primerFolio: 1.5,
                folioAdicional: 0.2
            }
        },
        "Actos no constitutivos": {
            "Acta de asamblea y junta directiva de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 2, primerFolio: 1.0, folioAdicional: 0.05 },
            "Aumento de capital de empresa mercantil": { tipo: "porcentaje", articulo: 4, numeral: 14, porcentajeCapital: 0.02 },
            "Cambio de domicilio nacional de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 15, primerFolio: 3.0, folioAdicional: 0.2 },
            "Disolución de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 2, primerFolio: 1.0, folioAdicional: 0.05 },
            "Domiciliación de expediente de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 2, primerFolio: 1.0, folioAdicional: 0.05 },
            "Fusión de compañías": { tipo: "petro", articulo: 4, numeral: 18, primerFolio: 5.0, folioAdicional: 0.05 },
            "Liquidación de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 2, primerFolio: 1.0, folioAdicional: 0.05 },
            "Modificación al documento de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 2, primerFolio: 1.0, folioAdicional: 0.05 },
            "Nombramiento de junta directiva de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 2, primerFolio: 1.0, folioAdicional: 0.05 },
            "Prórroga de duración de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 2, primerFolio: 1.0, folioAdicional: 0.05 },
            "Reducción de capital de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 7, primerFolio: 0.8, folioAdicional: 0.05 },
            "Renuncia a la denominación de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 7, primerFolio: 0.8, folioAdicional: 0.05 },
            "Solicitud de agregado": { tipo: "petro", articulo: 4, numeral: 8, primerFolio: 0.6, folioAdicional: 0.04 },
            "Solicitud de agregado de publicación": { tipo: "petro", articulo: 4, numeral: 8, primerFolio: 0.6, folioAdicional: 0.04 },
            "Transformación de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 7, primerFolio: 0.8, folioAdicional: 0.05 },
            "Venta de acciones de empresa mercantil": { tipo: "petro", articulo: 4, numeral: 17, primerFolio: 2.0, folioAdicional: 0.05 },
            "Venta de cuotas de participación": { tipo: "petro", articulo: 4, numeral: 4, primerFolio: 2.0, folioAdicional: 0.05 },
            "Venta de fondo de comercio": { tipo: "petro", articulo: 4, numeral: 4, primerFolio: 2.0, folioAdicional: 0.05 }
        },
        "Otros actos": {
            "Capitulación matrimonial": { tipo: "petro", articulo: 4, numeral: 5, primerFolio: 1.0, folioAdicional: 0.05 },
            "Contratos de adhesión": {}, // Pendiente
            "Declaración sucesoral": {}, // Pendiente
            "Factores mercantiles": { tipo: "petro", articulo: 4, numeral: 5, primerFolio: 1.0, folioAdicional: 0.05 },
            "Fideicomisos": {}, // Pendiente
            "Poderes personas jurídicas": { tipo: "petro", articulo: 4, numeral: 5, primerFolio: 1.0, folioAdicional: 0.05 },
            "Poderes personas naturales": { tipo: "petro", articulo: 4, numeral: 5, primerFolio: 1.0, folioAdicional: 0.05 }
        },
        "Archivo": {
            "Copia certificada fotostática": { tipo: "petro", articulo: 4, numeral: 12, primerFolio: 0.09, folioAdicional: 0.01 },
            "Copia simple fotostática": { tipo: "petro", articulo: 4, numeral: 12, primerFolio: 0.03, folioAdicional: 0.01 },
            "Sellado de Libros": { tipo: "petro", articulo: 4, numeral: 10, primerFolio: 0.1, folioAdicional: 0.01 }
        }
    },
    "Notaría": {
        "Documento Autenticado": 2,
        "Poder General": 3,
        "Poder Especial": 2,
    },
    "Registro Principal": {
        "Copias certificadas": {
            "Acta de defunción (emitida por registro civil/otros entes civiles)": 0,
            "Acta de matrimonio (emitida por registro civil/otros entes civiles)": 0,
            "Acta de matrimonio (inscrita en registro principal)": 0,
            "Acta de nacimiento (emitida por registro civil/otros entes civiles)": 0,
            "Actas constitutivas (asoc/soc/fundac inscrita en registro principal)": 0,
            "Actas de asamblea (asoc/soc/fundac inscrita en registro principal)": 0,
            "Asociaciones (asoc/soc/fundac inscrita en registro principal)": 0,
            "Corporaciones de carácter privado (asoc/soc/fundac inscrita en registro principal)": 0,
            "Declaración de voluntad (inscrita en registro principal)": 0,
            "Decreto de adopción (emitida por registro civil/otros entes civiles)": 0,
            "Fundaciones (asoc/soc/fundac inscrita en registro principal)": 0,
            "Inserción acta de matrimonio (emitida por registro civil/otros entes civiles)": 0,
            "Inserción acta de nacimiento (emitida por registro civil/otros entes civiles)": 0,
            "Reconocimiento posterior (emitida por registro civil/otros entes civiles)": 0,
            "Sentencia de interdicción (inscrita en registro principal)": 0,
            "Sentencias de divorcio (inscrita en registro principal)": 0,
            "Separación de cuerpos (inscrita en registro principal)": 0,
            "Sociedades civiles (asoc/soc/fundac inscrita en registro principal)": 0,
            "Título universitario (inscrita en registro principal)": 0
        },
        "Protocolización": {
            "Actas de asamblea (asambleas ONG)": 0,
            "Doctor Honoris Causa (título universitario)": 0,
            "Nulidad de acta de asamblea y del asiento registral (emitidas por tribunales)": 0,
            "Sentencia de adopción (emitidas por tribunales)": 0,
            "Sentencia de impugnación de paternidad (emitidas por tribunales)": 0,
            "Sentencia de inquisición de paternidad (emitidas por tribunales)": 0,
            "Sentencia de interdicción (emitidas por tribunales)": 0,
            "Sentencias de divorcio (emitidas por tribunales)": 0,
            "Separación de cuerpos (emitidas por tribunales)": 0,
            "Título universitario (título universitario)": 0
        },
        "Legalizaciones": {
            "Acción mero declarativa (emitidas por tribunales)": 0,
            "Aclaratoria de acta de matrimonio (emitida por registro civil/otros entes civiles)": 0,
            "Aclaratoria de acta de nacimiento (emitida por registro civil/otros entes civiles)": 0,
            "Aclaratoria (inscrita en registro público)": 0,
            "Acta constitutiva organizaciones civiles de carácter privado (ONG registro público)": 0,
            "Acta constitutiva sociedades mercantiles (registro mercantil)": 0,
            "Acta de asamblea organizaciones civiles de carácter privado (ONG registro público)": 0,
            "Acta de asamblea sociedades mercantiles (registro mercantil)": 0,
            "Acta de defunción (emitida por registro civil/otros entes civiles)": 0,
            "Acta de matrimonio (emitida por registro civil/otros entes civiles)": 0,
            "Acta de matrimonio (emitidas por tribunales)": 0,
            "Acta de nacimiento (emitida por registro civil/otros entes civiles)": 0,
            "Actas constitutivas (asoc/soc/fundac inscrita en registro principal)": 0,
            "Actas de asamblea (asoc/soc/fundac inscrita en registro principal)": 0,
            "Adendum (notaría)": 0,
            "Autorización de representación judicial (emitidas por tribunales)": 0,
            "Autorización judicial de representación en el extranjero (emitidas por tribunales)": 0,
            "Autorización para viaje de niño, niña y adolescentes (notaría)": 0,
            "Autorizaciones (notaría)": 0,
            "Cambio de residencia internacional (emitidas por tribunales)": 0,
            "Cancelación de hipoteca 1er grado (inscrita en registro público)": 0,
            "Capitulaciones matrimoniales (inscrita en registro público)": 0,
            "Capitulaciones matrimoniales (notaría)": 0,
            "Carta de soltería (otros)": 0,
            "Carta rogatoria (emitidas por tribunales)": 0,
            "Cartel de citación (emitidas por tribunales)": 0,
            "Certificación de nacido vivo (emitida por registro civil/otros entes civiles)": 0,
            "Certificación de no naturalizado (emitida por registro civil/otros entes civiles)": 0,
            "Certificado de solvencia de sucesiones (emitida por registro civil/otros entes civiles)": 0,
            "Certificado de solvencia de sucesiones (inscrita en registro principal)": 0,
            "Cesiones onerosas (notaría)": 0,
            "Colocación familiar (emitidas por tribunales)": 0,
            "Constancia de no existencia (emitida por registro civil/otros entes civiles)": 0,
            "Constancia de residencia (otros)": 0,
            "Constancia de viudez (otros)": 0,
            "Constancias (emitida por registro civil/otros entes civiles)": 0,
            "Contratos (notaría)": 0,
            "Dación en pago con valor estimado (inscrita en registro público)": 0,
            "Declaración de no poseer vivienda (notaría)": 0,
            "Declaración de voluntad (notaría)": 0,
            "Declaraciones juradas (notaría)": 0,
            "Declaratoria de nacionalidad (emitida por registro civil/otros entes civiles)": 0,
            "Decreto de adopción (emitida por registro civil/otros entes civiles)": 0,
            "Disolución de unión estable de hecho (emitida por registro civil/otros entes civiles)": 0,
            "Disolución de unión estable de hecho (emitidas por tribunales)": 0,
            "Donación (notaría)": 0,
            "Edicto (emitidas por tribunales)": 0,
            "Exequatur (emitidas por tribunales)": 0,
            "Expediente de sociedades de mercantiles (registro mercantil)": 0,
            "Extradición (emitidas por tribunales)": 0,
            "Extradición (inscrita en registro principal)": 0,
            "Factores mercantiles (registro mercantil comercial)": 0,
            "Fe de vida (otros)": 0,
            "Fianzas (notaría)": 0,
            "Fideicomiso (notaría)": 0,
            "Garantía (notaría justificativos)": 0,
            "Impugnación de reconocimiento (emitidas por tribunales)": 0,
            "Impugnación y inquisición de paternidad (emitidas por tribunales)": 0,
            "Inhabilitación de adulto (emitidas por tribunales)": 0,
            "Inserción acta de defunción (emitida por registro civil/otros entes civiles)": 0,
            "Inserción acta de matrimonio (emitida por registro civil/otros entes civiles)": 0,
            "Inserción acta de nacimiento (emitida por registro civil/otros entes civiles)": 0,
            "Inserción acta de naturalización (emitida por registro civil/otros entes civiles)": 0,
            "Inserción acta de reconocimiento (emitida por registro civil/otros entes civiles)": 0,
            "Inspección judicial (emitidas por tribunales)": 0,
            "Invitaciones a extranjeros (notaría)": 0,
            "Justificativo de carga familiar (emitidas por tribunales)": 0,
            "Justificativo de testigos (emitidas por tribunales)": 0,
            "Justificativo de únicos y universales herederos (emitidas por tribunales)": 0,
            "Justificativo de unión estable de hecho (emitida por registro civil/otros entes civiles)": 0,
            "Justificativo de unión estable de hecho (notaría)": 0,
            "Justificativos con fines legales (emitidas por tribunales)": 0,
            "Justificativos con fines legales (notaría justificativos)": 0,
            "Justificativos con fines matrimoniales (notaría justificativos)": 0,
            "Liberación de hipoteca (inscrita en registro público)": 0,
            "Liberación de hipoteca (notaría)": 0,
            "Medida anticipada preventiva de custodia (emitidas por tribunales)": 0,
            "Medida cautelar de embargo (emitidas por tribunales)": 0,
            "Participación y liquidación hereditaria (inscrita en registro público)": 0,
            "Poder (inscrita en registro público)": 0,
            "Poder (notaría)": 0,
            "Poder (registro mercantil)": 0,
            "Reconocimiento (emitida por registro civil/otros entes civiles)": 0,
            "Reconocimiento (emitidas por tribunales)": 0,
            "Reconocimiento (inscrita en registro principal)": 0,
            "Reconocimiento (inscrita en registro público)": 0,
            "Reconocimiento (notaría)": 0,
            "Reconstrucción de expediente de divorcio (emitidas por tribunales)": 0,
            "Rectificación de acta de defunción (emitida por registro civil/otros entes civiles)": 0,
            "Rectificación de acta de matrimonio (emitida por registro civil/otros entes civiles)": 0,
            "Rectificación de acta de matrimonio (emitidas por tribunales)": 0,
            "Rectificación de partida (emitida por registro civil/otros entes civiles)": 0,
            "Renuncia de derecho (notaría)": 0,
            "Renuncia de herencia (inscrita en registro público)": 0,
            "Renuncia de herencia (notaría)": 0,
            "Renuncia de nacionalidad (emitida por registro civil/otros entes civiles)": 0,
            "Renuncia de poder (inscrita en registro público)": 0,
            "Renuncia de poder (notaría)": 0,
            "Revocatoria de contratos (notaría)": 0,
            "Revocatoria de poder (inscrita en registro público)": 0,
            "Revocatoria de poder (notaría)": 0,
            "Sentencia de adopción (emitidas por tribunales)": 0,
            "Sentencia de adopción (inscrita en registro principal)": 0,
            "Sentencia de autorización de viaje (emitidas por tribunales)": 0,
            "Sentencia de autorización de viaje (inscrita en registro principal)": 0,
            "Sentencia de ejercicio unilateral de patria potestad (emitidas por tribunales)": 0,
            "Sentencia de ejercicio unilateral de patria potestad (inscrita en registro principal)": 0,
            "Sentencia de herederos únicos y universales (emitidas por tribunales)": 0,
            "Sentencia de herederos únicos y universales (inscrita en registro principal)": 0,
            "Sentencia de homologación (emitidas por tribunales)": 0,
            "Sentencia de sobreseimiento (emitidas por tribunales)": 0,
            "Sentencia de tutela (inscrita en registro público)": 0,
            "Sentencia definitiva (emitidas por tribunales)": 0,
            "Sentencia (emitidas por tribunales)": 0,
            "Sentencia (inscrita en registro principal)": 0,
            "Sentencia (inscrita en registro público)": 0,
            "Sentencia interlocutoria (emitidas por tribunales)": 0,
            "Sentencias de divorcio (emitidas por tribunales)": 0,
            "Sentencias de divorcio (inscrita en registro principal)": 0,
            "Sentencias de divorcio (inscrita en registro público)": 0,
            "Separación de cuerpos (emitidas por tribunales)": 0,
            "Solicitud de agregado (registro mercantil)": 0,
            "Sustitución de poder (inscrita en registro público)": 0,
            "Sustitución de poder (notaría)": 0,
            "Testamento (inscrita en registro público)": 0,
            "Testamento (notaría)": 0,
            "Traducción pública (notaría)": 0,
            "Tutela (emitidas por tribunales)": 0,
            "Venta de bien mueble (notaría)": 0,
            "Venta (inscrita en registro público)": 0,
            "Venta (notaría)": 0
        },
        "Notas al margen": {
            "Acta de defunción (emitida por registro civil/otros entes civiles)": 0,
            "Autenticaciones de notaría (notaría)": 0,
            "Exequatur (inscrita en registro principal)": 0,
            "Legitimación por consiguiente de matrimonio (emitida por registro civil/otros entes civiles)": 0,
            "Modificación de título universitario (inscrita en registro principal)": 0,
            "Nulidad de acta de asamblea y del asiento registral (emitidas por tribunales)": 0,
            "Nulidad de acta de nacimiento (emitida por registro civil/otros entes civiles)": 0,
            "Reconocimiento posterior (inscrita en registro principal)": 0,
            "Rectificación de acta de defunción (emitida por registro civil/otros entes civiles)": 0,
            "Rectificación de acta de defunción (emitidas por tribunales)": 0,
            "Rectificación de acta de matrimonio (inscrita en registro principal)": 0,
            "Rectificación de partida (emitida por registro civil/otros entes civiles)": 0,
            "Rectificación de partida (emitidas por tribunales)": 0,
            "Recuperación de nacionalidad (inscrita en registro principal)": 0,
            "Renuncia de nacionalidad (inscrita en registro principal)": 0,
            "Revocatoria de poder (notaría)": 0,
            "Sentencia de adopción (inscrita en registro principal)": 0,
            "Sentencia de impugnación de paternidad (inscrita en registro principal)": 0,
            "Sentencia de inquisición de paternidad (inscrita en registro principal)": 0,
            "Sentencia de interdicción (inscrita en registro principal)": 0,
            "Sentencias de divorcio (inscrita en registro principal)": 0
        }
    }
};
